### PR TITLE
Add iproute2 to base image

### PR DESCRIPTION
**Pull request by jaredledvina**
Enables the `ansible_default_ipv4` variable to be populated
Closes issue #5

Current behaviour:
```
root@c4c60066e036:/# ansible localhost -m setup | grep ansible_default_ipv4
root@c4c60066e036:/#
```

And if you install `iproute2`:
```
root@c4c60066e036:/# ansible localhost -m setup | grep ansible_default_ipv4 -A 11
        "ansible_default_ipv4": {
            "address": "172.17.0.2",
            "alias": "eth0",
            "broadcast": "172.17.255.255",
            "gateway": "172.17.0.1",
            "interface": "eth0",
            "macaddress": "02:42:ac:11:00:02",
            "mtu": 1500,
            "netmask": "255.255.0.0",
            "network": "172.17.0.0",
            "type": "ether"
        },
```

### CODE REVIEW

**Comment by jaredledvina** [comment]
@geerlingguy - Any chance you might be able to check this PR out?

**Comment by geerlingguy** [comment]
This looks like a decent addition, as that info is nice to have. I would like to make sure I add it to my other base images too, though, as I don't want to get the basic set of packages too much out of sync (I like to swap out base images when testing 14-16, 16-8, Debian 8-9, etc.).

So I would like to merge, but will need to wait until I have an hour or so to update the rest of my base images too.

**Comment by jaredledvina** [comment]
Sounds good to me @geerlingguy, it's been a bit since I looked really closely here (I also switched to the `dokken` images for other reasons) but, I think only Ubuntu 16.04 and 18.04 need `iproute2`. I _think_ the other's might get the `ip` command via another package already (it might already be in the base image packages too.). 

If I find some time this weekend, I'll look a bit more and open some PR's as necessary.

**Comment by gofrolist** [comment]
What about to merge this PR? This is definitely needed to work with networks in ansible/molecule.
And I don't like to have this part of code in playbook.yml as a workaround
```
  pre_tasks:
    - name: Ensure that iproute package is installed (Ubuntu1604)
      package:
        name: iproute2
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'
    - name: Gather Facts network subset
      setup:
        gather_subset:
          - network
      when: ansible_default_ipv4 is undefined
```

**Comment by geerlingguy** [comment]
This has been merged via PR checkout / commit. Thanks!

**Pull request closed without merging**
